### ISSUE TITLE
Give feedback to Konna on how she made the logo and the socials 

### ISSUE THREAD

**Issue by konnaang** [Ludik-Studio/site#4]
![feedback1](https://user-images.githubusercontent.com/92678558/146624344-c922983e-a711-4528-a420-d3e3dcfae6d2.png)
![feedback2](https://user-images.githubusercontent.com/92678558/146624347-c94bf7de-a907-4875-b2eb-1e0c63cdfc20.png)

**Comment by joskar** [comment]
While you did a good job I had to rollback in order to reduce the custom code that we have for the theme.
Spectral is using font awesome which means you should be able to use any brand logo my writing  

https://fontawesome.com/v5.15/icons?d=gallery&q=facebook 
by adding a class to an `a` element for example for facebook you should add `icon brands fa-lg fa-facebook-square`

also your css approach while it might be working.
it is problematic because you need to control each element manually.
Instead you should create a container and use display flex with column wrap
which means that each element will take the space that it needs and also 
they will be displayed the underneath the other without you needed to extra work.
For more details on flexbox check [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox)

snippet of the css to align the elements the way I explained above.
check thew new index [file](https://github.com/Ludik-Studio/site/pull/13/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R24) for the html
 
```
.social-networks {
    position: relative;
    display: flex;
    flex-flow: column wrap;
  }
  .network {
    box-sizing: border-box;
    padding: 20px;
    flex: 1;
    text-align: center;
  }
  ```
